---
- hosts: docker-dev
  become: yes
  vars:
    sql_root_password: 'secretsql'

  tasks:

    - name: Create metmini database
      mysql_db:
        name: metminidb
        login_user: root
        login_password: "{{ sql_root_password }}"
        login_host: localhost
        state: present

    - name: Copy actual_table.sql to server
      template: src=actual_table.sql dest=/tmp/actual_table.sql owner=vagrant group=users

    - name: Create the actual table
      command: mysql "-u root -p{{ sql_root_password }} < /tmp/actual_table.sql"

    - name: Remove the actual table sql file from the server
      command: rm -f /tmp/actual_table.sql
