---
- hosts: docker-dev
  become: yes

  tasks:
    - name: Copy docker-compose to server
      template: src=docker-compose.yml dest=/etc/docker-compose.yml owner=root group=root

    - name: Pull latest container
      shell: "version={{ lookup('env', 'version') }} stage={{ lookup('env', 'stage') }} sql_db_hostname={{ lookup('env', 'sql_db_hostname') }} /usr/bin/docker-compose -f /etc/docker-compose.yml pull"

    - name: Start up the new container
      shell: >
      "version={{ lookup('env', 'version') }}
      stage={{ lookup('env', 'stage') }}
      sql_db_hostname={{ lookup('env', 'sql_db_hostname') }}
      /usr/bin/docker-compose -f /etc/docker-compose.yml up &"
