---
- hosts: docker-dev

  tasks:
    - name: Copy docker-compose to server
      template: src=docker-compose.yml dest=/etc/docker-compose.yml owner=root group=root

    - name: Bring in new container
      command: >
      /usr/bin/docker-compose -f /etc/docker-compose.yml pull &&
      /usr/bin/docker-compose -f /etc/docker-compose.yml -d up
