# This runs on the Docker Host
# add to rc.local:
# docker-compose -d -f /etc/docker-compose.yml up

version: '3'

services:
  actuald:
    container_name: actuald
    image: registry:5000/actuald:$version
    logging:
      driver: syslog
    environment:
      STAGE: $stage
      VERSION: $version
      SQL_DB_HOSTNAME: $sql_db_hostname
