---
- hosts: metmini-itg
  become: yes
  sql_root_password: "secretsql"

  tasks:

    - name: Run mysql_install_db
      command: mysql_install_db --datadir=/data/db

    - name: Start MariaDB service
      service: name=mariadb state=started enabled=yes

    - name: Is root password set?
      command: mysql -u root --execute "SELECT NOW()"
      register: is_root_password_set
      ignore_errors: yes

    - name: Delete anonymous users
      mysql_user: user="" state="absent"
      when: is_root_password_set.rc == 0

    - name: Set root password
      mysql_user: user=root password={{ sql_root_password }} host=localhost
      when: is_root_password_set.rc == 0

    - name: Create metmini database
      mysql_db:
        name: metminidb
        login_user: root
        login_password: {{mysql_root_password }}
        login_host: localhost
        state: present
      when: is_root_password_set.rc == 0

    - name: copy actual_table.sql to server
      template: src=actual_table.sql dest=/tmp/actual_table.sql; owner=root group=root
    when: is_root_password_set.rc == 0

    - name: create the actual table
      command: mysql "-u root -p{{ mysql_root_password }} < /tmp/actual_table.sql"
    when: is_root_password_set.rc == 0

    - name: remove the actual table sql file from the server
      command: rm -f /tmp/actual_table.sql
    when: is_root_password_set.rc == 0
