# This runs on the Docker Host
# add to rc.local:
# docker-compose -d -f /etc/docker-compose.yml up
# This is for the production environment on mrdell

version: '3'

services:
  actuald:
    image: registry:5000/actuald:1.0.0
    environment:
      SQL_DB_HOSTNAME: 192.168.1.180
      STAGE: PRD
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
