# This runs on the Docker Host
# add to rc.local:
# docker-compose -d -f /etc/docker-compose.yml up
# This is for the production environment on mrdell
# Container version is locked to a version
# The master is on mrdell

version: '3'

services:
  actuald:
    container_name: actuald
    image: registry:5000/actuald:1.0.0
    environment:
      SQL_DB_HOSTNAME: 192.168.1.180
      STAGE: PRD
